[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
gas_reports = ["NotificationAlertSystem"]
remappings = [
    "forge-std/=lib/forge-std/src/"
]

# Sonic-specific configurations
[profile.sonic]
sonic_blaze = "https://rpc.blaze.soniclabs.com"
chain_id = 57054

# For testing
[profile.test]
src = "test"
out = "out"
libs = ["lib"]
verbosity = 3
gas_reports = ["*"]
# Increase the fuzz test runs since we have complex notification logic
fuzz = { runs = 500 }

# For script runs (deployment)
[profile.script]
src = "script"
out = "artifacts"
libs = ["lib"]
broadcast = "broadcast"

# For CI/CD (with higher fuzzing runs)
[profile.ci]
fuzz = { runs = 1000 }
verbosity = 4